[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  # bundle @netlify/blobs to avoid ESM/CJS runtime mismatch

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"


